<<<<<<< HEAD
openapi: 3.0.0
info:
  title: Recipe App API
  version: 1.0.0
  description: API documentation for Recipe App including Category, Recipe, and OpenAI endpoints.

servers:
  - url: https://be-tan-theta.vercel.app
  - url: http://localhost:5000
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter JWT token

  parameters:
    AuthorizationHeader:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
        default: 1234

paths:
  /api/categories:
    get:
      summary: Get all categories
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of categories

    post:
      summary: Create a new category
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Category created

  /api/categories/{id}:
    delete:
      summary: Delete category by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted successfully

  /api/recipes:
    get:
      summary: Get all recipes
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of recipes

    post:
      summary: Create a new recipe
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                ingredients:
                  type: array
                  items:
                    type: string
                instructions:
                  type: string
      responses:
        '201':
          description: Recipe created

  /api/recipes/{id}:
    get:
      summary: Get a recipe by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Single recipe

    delete:
      summary: Delete a recipe by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted successfully
    post:
      summary: Generate recipe content using OpenAI
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
      responses:
        '200':
          description: Generated response from OpenAI
=======
openapi: 3.0.0
info:
  title: Recipe App API
  version: 1.0.0
  description: API documentation for Recipe App including Category, Recipe, and OpenAI endpoints.

servers:
  - url: https://be-tan-theta.vercel.app
  - url: http://localhost:5000
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter JWT token

  parameters:
    AuthorizationHeader:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
        default: 1234

paths:
  /api/categories:
    get:
      summary: Get all categories
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of categories

    post:
      summary: Create a new category
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Category created

  /api/categories/{id}:
    delete:
      summary: Delete category by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted successfully

  /api/recipes:
    get:
      summary: Get all recipes
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of recipes

    post:
      summary: Create a new recipe
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                ingredients:
                  type: array
                  items:
                    type: string
                instructions:
                  type: string
      responses:
        '201':
          description: Recipe created

  /api/recipes/{id}:
    get:
      summary: Get a recipe by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Single recipe

    delete:
      summary: Delete a recipe by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted successfully
    post:
      summary: Generate recipe content using OpenAI
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
      responses:
        '200':
          description: Generated response from OpenAI
>>>>>>> a9ba5b25307e1e51fb4bcd3920e822172e771c75
